package enitity;
// Generated Jul 8, 2020 10:03:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Informasikasuscovid generated by hbm2java
 */
public class Informasikasuscovid  implements java.io.Serializable {


     private Integer id;
     private int positif;
     private int sembuh;
     private int meningal;
     private Date tanggalBuat;

    public Informasikasuscovid() {
    }

    public Informasikasuscovid(int positif, int sembuh, int meningal, Date tanggalBuat) {
       this.positif = positif;
       this.sembuh = sembuh;
       this.meningal = meningal;
       this.tanggalBuat = tanggalBuat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPositif() {
        return this.positif;
    }
    
    public void setPositif(int positif) {
        this.positif = positif;
    }
    public int getSembuh() {
        return this.sembuh;
    }
    
    public void setSembuh(int sembuh) {
        this.sembuh = sembuh;
    }
    public int getMeningal() {
        return this.meningal;
    }
    
    public void setMeningal(int meningal) {
        this.meningal = meningal;
    }
    public Date getTanggalBuat() {
        return this.tanggalBuat;
    }
    
    public void setTanggalBuat(Date tanggalBuat) {
        this.tanggalBuat = tanggalBuat;
    }




}


