package enitity;
// Generated Jul 8, 2020 10:03:16 AM by Hibernate Tools 4.3.1



/**
 * Rumahsakitrujukan generated by hbm2java
 */
public class Rumahsakitrujukan  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String alamat;
     private String nomorTelepon;

    public Rumahsakitrujukan() {
    }

    public Rumahsakitrujukan(String nama, String alamat, String nomorTelepon) {
       this.nama = nama;
       this.alamat = alamat;
       this.nomorTelepon = nomorTelepon;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNomorTelepon() {
        return this.nomorTelepon;
    }
    
    public void setNomorTelepon(String nomorTelepon) {
        this.nomorTelepon = nomorTelepon;
    }




}


